# This is a GitLab CI configuration to build the project as a docker image
# The file is generic enough to be dropped in a project containing a working Dockerfile
# Mentioned here: https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/

#v1.7

# do not use "latest" here, if you want this to work in the future
image: docker:18

stages:
  - build

variables:
  DOCKER_DRIVER: overlay

# Use this if your GitLab runner does not use socket binding
services:
   - docker:dind

before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab Edwin
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

Build:
  stage: build
  script:
    - >
      docker build
      --tag $CI_REGISTRY_IMAGE
      .
    - docker push $CI_REGISTRY_IMAGE
